name: playground_dart
description: A LeetCode playground for Dart.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  benchmark_harness: ^2.2.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
